# Cloudflare Pages configuration for Moodeight
name = "moodeight"
compatibility_date = "2025-01-10"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables
# Note: SUPABASE_SERVICE_ROLE_KEY must be set as encrypted secret in Cloudflare Dashboard
# All VITE_* variables are build-time variables that get embedded in the frontend bundle
[vars]
VITE_SUPABASE_URL = "https://jqjkdfbgrtdlkkfwavyq.supabase.co"
# Add your Supabase publishable key here (safe to commit - it's designed to be public)
VITE_SUPABASE_ANON_KEY = "sb_publishable_SDbpRmwVr40Dspe_XmdjaQ_mTn1g48L"
# Optional: Showcase board ID for homepage
# VITE_SHOWCASE_BOARD_ID = "your-board-uuid-here"

# IMPORTANT: SUPABASE_SERVICE_ROLE_KEY is a SECRET
# It MUST be set as encrypted variable in Cloudflare Dashboard (not in this file)
